# syntax = docker/dockerfile:1.2
FROM rust:1.75.0 as base
RUN cargo install cargo-chef@0.1.62 --locked
RUN rustup component add rustfmt
RUN apt-get update && apt-get install -y clang cmake ssh
WORKDIR /app

FROM base AS plan
COPY . .
WORKDIR /app
RUN cargo chef prepare --recipe-path recipe.json

FROM base as build
COPY --from=plan /app/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json
COPY . .
RUN cargo build --release --bin solana-lite-rpc-benchrunner-service

FROM debian:bookworm-slim as run
RUN apt-get update && apt-get -y install ca-certificates libc6 libssl3 libssl-dev openssl

COPY openssl-legacy.cnf /etc/ssl/openssl-legacy.cnf

COPY --from=build /app/target/release/solana-lite-rpc-benchrunner-service /usr/local/bin/

ENV OPENSSL_CONF=/etc/ssl/openssl-legacy.cnf

CMD solana-lite-rpc-benchrunner-service \
    --bench-interval 600000 \
    --tx-count 10 \
    --prio-fees 10000 --prio-fees 1000 --prio-fees 0
