name: Deploy benchrunner to Fly

on:
  push:
      tags:
        - 'production/benchrunner-*'
        - 'experimental/benchrunner-*'

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Setup Fly
        uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Deploy solana-lite-rpc-benchrunner
        run: flyctl deploy -c cd/solana-lite-rpc-benchrunner.toml --remote-only
